### PR TITLE
Added user detail state inside AuthProvider

### PR DESCRIPTION
**Pull request by johnfa1508**

### CODE REVIEW

**Review by JosteinRuen — APPROVED** [review]
Great change

**Review by Julia-Lindgren — DISMISSED** [review]
Incredible

**Review by George-Alexander-S — APPROVED** [review]
LGTM

**Review by alihaiderkhannn — APPROVED** [review]
Approved

**Review by allendewilzin — APPROVED** [review]

**Comment by allendewilzin** [comment]
👍🏻

**Pull request merged**
